#!/bin/bash
# This script sets rail group of power rails to 0x0 (no rail group)
# Essentially, it disables safety feature of PMIC initiating POR when glitch is detected on power rails

grep j721e /proc/device-tree/compatible | grep -q sk
if [ $? -ne 0 ]
then
    exit 0
fi

#set bus 2, address 0x48 (PMIC A address), 0x41,42,43 register address, with value 0x0
i2cset -f -y 0x0 0x48 0x41 0x0
i2cset -f -y 0x0 0x48 0x42 0x0
i2cset -f -y 0x0 0x48 0x43 0x0

#same as above for PMIC B
i2cset -f -y 0x0 0x4C 0x41 0x0
i2cset -f -y 0x0 0x4C 0x42 0x0
i2cset -f -y 0x0 0x4C 0x43 0x0

is_failed=false
#check PMIC A register
for i in {0..2}
do
   i2cget -y 0x0 0x48 $((0x41+$i)) | grep '0x00' &> /dev/null
   if [[ $? -ne "0x00" ]]; then
      echo "PMIC A register value failed to change"
      is_failed=true
   fi
done

#check PMIC B register
for i in {0..2}
do
   i2cget -y 0x0 0x4C $((0x41+$i)) | grep '0x00' &> /dev/null
   if [[ $? -ne 0 ]]; then
      echo "PMIC B register value failed to change"
      is_failed=true
   fi
done

if [ $is_failed = true ] ; then
   exit 1
fi

echo "PMIC registers successfully updated!"
exit 0
